name: build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        env:
          RENPY_VERSION: 7.4.11
          RENKIT_VERSION: 1.2.1
        with:
          push: true
          tags: infinitecanvas/renpy:latest,infinitecanvas/renpy:RenPy$RENPY_VERSION-RenKit$RENKIT_VERSION