name: build-and-push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: 
            RenPyVerArg="7.4.11"
            RenKitVerArg="1.2.1"
          push: true
          tags: infinitecanvas/renpy:latest,infinitecanvas/renpy:RenPy7.4.11-RenKit1.2.1